name: Backend CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - run: npm ci

      # - run: npm run lint

      - run: npm run build

      # 👇 This will NOT start server or DB now
      - name: Verify build runs
        run: node dist/server.js
        env:
          NODE_ENV: ci
